version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: penman-backend:1.0
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: penman-frontend:1.0
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
